// @parity test/pdf-report
//
// A saved measurement's PDF report, as the measurement list exports it (reportForMeasurement), read back
// line by line and compared with the expected lines beside its fixture (`<fixture>.pdf.txt`): each line's
// page, its height on the page and its words. A line's height is its baseline's distance from the page's
// top — for a line mixing sizes, the baseline of its largest text — and must be within 1 pt of the
// expected. Words are compared with whitespace removed. The measurement's date and the "Generated by …"
// line are matched by position only (they depend on the locale, the time and the build). The expected
// lines are Swift's; Swift PDFReportTests and the Python suite have the same cases and expected files.
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs'
import { parseGuitarTapFile } from '../src/measurement'
import { reportForMeasurement } from '../src/presentation/measurementImage'
import { formatDisplayDate } from '../src/format/date'
import { installCanvasStandIn } from './support/canvasStandIn'

/** Each fixture, through the report its kind uses. */
const FIXTURES = [
  '5-guitar-comparison-1776708138',
  'annotation-override-1790037028',
  'annotation-override-python-1790037332',
  'brace-umik-1-3-tap-swift-mac-1785359380',
  'brace-umik-1-python-mac-1785442624',
  'brace-umik-1-swift-mac-1785359411',
  'comparison-long-name-1776708138',
  'contreras-classical-1774731564',
  'dws-2024-umik-1-3-tap-swift-mac-1785359425',
  'dws-2024-umik-1-3-tap-web-mac-1785440737',
  'dws-2024-umik-1-python-mac-1784225140',
  'dws-2024-umik-1-swift-mac-1784225155',
  'dws-2024-umik-1-swift-mac-1785359434',
  'dws-2024-umik-1-web-mac-1784225174',
  'plate-umik-1-3-tap-swift-ipad-1784314709',
  'plate-umik-1-3-tap-swift-mac-1785359465',
  'plate-umik-1-swift-mac-1785359486',
  'plate-umik-1-web-mac-1785440769',
]

/** pdf.js's metrics for the PDF standard fonts (Helvetica …), shipped with pdfjs-dist. */
const STANDARD_FONTS = `${process.cwd()}/node_modules/pdfjs-dist/standard_fonts/`

/** One line of a page: its page index, its baseline's distance from the page's top, and its text. */
interface Line {
  page: number
  baseline: number
  text: string
}

const show = (l: Line) => `${l.page}\t${l.baseline.toFixed(1)}\t${l.text}`

/** The pages' lines by position: each text run placed by its transform, grouped into lines by baseline
 *  (top to bottom), each line left to right, placed at the baseline of its largest run. */
async function linesOf(pdf: Uint8Array): Promise<Line[]> {
  const doc = await getDocument({ data: pdf, standardFontDataUrl: STANDARD_FONTS }).promise
  const out: Line[] = []
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i)
    const height = page.getViewport({ scale: 1 }).height
    const runs = (await page.getTextContent()).items
      .flatMap((item) =>
        'str' in item && item.str.trim()
          ? [{
              baseline: height - (item.transform[5] as number),
              x: item.transform[4] as number,
              size: Math.hypot(item.transform[2] as number, item.transform[3] as number),
              text: item.str.trim(),
            }]
          : [],
      )
      .sort((a, b) => a.baseline - b.baseline)
    const rows: (typeof runs)[] = []
    for (const run of runs) {
      const last = rows[rows.length - 1]
      if (last && Math.abs(last[0]!.baseline - run.baseline) < 3) last.push(run)
      else rows.push([run])
    }
    for (const row of rows) {
      const largest = row.reduce((m, r) => (r.size > m.size + 0.01 ? r : m))
      out.push({ page: i - 1, baseline: largest.baseline, text: row.sort((a, b) => a.x - b.x).map((r) => r.text).join(' ') })
    }
  }
  return out
}

/** The lines joined, without whitespace, in Unicode compatibility form (a ligature reads as its letters). */
const squeezed = (lines: string[]) => lines.join('').normalize('NFKC').replace(/\s/g, '')

describe('PDF report', () => {
  beforeAll(() => installCanvasStandIn())

  for (const fixture of FIXTURES) {
    it(`${fixture} matches the expected lines`, async () => {
      const measurement = parseGuitarTapFile(readFileSync(`test/fixtures/${fixture}.guitartap`, 'utf8'))[0]!
      const report = await reportForMeasurement(measurement)
      const date = squeezed([formatDisplayDate(measurement.timestamp)])
      const actual = (await linesOf(new Uint8Array(await report.blob.arrayBuffer()))).map((l) => ({
        ...l,
        text: squeezed([l.text]) === date ? '<date>' : l.text.startsWith('Generated by') ? '<generated>' : l.text,
      }))
      const expected = readFileSync(`test/fixtures/${fixture}.guitartap.pdf.txt`, 'utf8')
        .split('\n')
        .filter(Boolean)
        .map((row) => {
          const [page, baseline, ...text] = row.split('\t')
          return { page: Number(page), baseline: Number(baseline), text: text.join('\t') }
        })
      const listing = `--- actual\n${actual.map(show).join('\n')}\n--- expected\n${expected.map(show).join('\n')}`
      expect(actual.length, `line count\n${listing}`).toBe(expected.length)
      actual.forEach((a, i) => {
        const e = expected[i]!
        const same = a.page === e.page && Math.abs(a.baseline - e.baseline) <= 1 && squeezed([a.text]) === squeezed([e.text])
        expect(same, `${show(a)} ≠ expected ${show(e)}\n${listing}`).toBe(true)
      })
    })
  }
})
